server:
  port: 8080
  contextPath: /
bosch:
  permissions:
    endpointUrl: https://permissions-api.apps.bosch-iot-cloud.com
    clientId: 174bbcf7-27c4-4dd4-af82-85a7fd353f6b
    clientSecret: 3ylEJ63RB6Hn6FQwSM1tmC
  things:
    alias: CR
    alias.password: bosch123
    endpointUrl : https://things.apps.bosch-iot-cloud.com
    wsEndpointUrl : wss://events.apps.bosch-iot-cloud.com
    apiToken: 70440375adbe4687bf5ebe4bffad61c5
    keystoreLocation : /secure/CRClient.jks
    trustStoreLocation : /secure/bosch-iot-cloud.jks
    trustStorePassword : jks
    solutionid: 0c3bf9ff-b40b-4adc-97fc-fb625c81b80e
    keystore:
      password: bosch123      
http:
  proxyUser: 
  proxyPassword:
  proxyHost: 
  proxyPort: 8080