# docker-compose.yml
vorto-jsonschema-generator-web:
  build: .
  container_name: vorto-jsonschema-generator
  ports:
   - 9003:9003
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-jsonschema
    - SERVER_PORT=9003
