# docker-compose.yml
vorto-ios-generator-web:
  build: .
  container_name: vorto-ios-generator
  ports:
   - 9004:9004
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-ios
    - SERVER_PORT=9004
