#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

version: '3'
services:
  repository:
    depends_on:
      - "db"
    image: eclipsevorto/vorto-repo:latest
    volumes:
      - ~/.vorto:/root/.vorto
    ports:
      - "8080:8080"
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  db:
    volumes:
       - /opt/mysql_data:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
networks:
  backend:
    driver: bridge
