#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

server:
  contextPath: /

repo:
  configFile: vorto-repository-config-mysql.json
  attachment:
    allowed:
      extension:

spring:
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    wait_timeout: 180
    validationInterval: 60    
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none

