# docker-compose.yml
vorto-markdown-generator-web:
  build: .
  container_name: vorto-markdown-generator
  ports:
   - 9007:9007
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-markdown
    - SERVER_PORT=9007
