
vorto:
  repository:
    base:
      path: https://localhost:8443/infomodelrepository
      
http:
  proxyHost:
  proxyPort:

server:
  port: 9443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: Vorto123!
    keyStoreType: jks
    keyAlias: vorto-selfsigned
  
github:
  client:
    clientId: ${github_clientid}
    clientSecret: ${github_secret}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - user
  resource:
    userInfoUri: https://api.github.com/user