# docker-compose.yml
vorto-webdevice-generator-web:
  build: .
  container_name: vorto-webdevice-generator
  ports:
   - 9000:9000
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-webdevice
    - SERVER_PORT=9000
