# docker-compose.yml
vorto-bosch-generator-web:
  build: .
  container_name: vorto-bosch-generator
  ports:
   - 9005:9005
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-bosch
    - SERVER_PORT=9005
