# docker-compose.yml
vorto-mqtt-generator-web:
  build: .
  container_name: vorto-mqtt-generator
  ports:
   - 9002:9002
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-mqtt
    - SERVER_PORT=9002
