#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

repo:
  configFile: vorto-repository-config-mysql-local_new.json
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    #url: jdbc:h2:file:${user.home}/.vorto
    url: jdbc:mysql://localhost:3306/vorto_schema?autoReconnect=true
    username: vorto
    password: vorto
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    wait_timeout: 180
    validationInterval: 60
    validationQuery: SELECT 1

server:
  port: 8080
  contextPath: /
  use-forward-headers: true
  admin: aedelmann,t-gauss

eidp_clientid: 123
eidp_secret: 123
# Original
#plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkJeyJrZXkiIDogImVjbGlwc2VkaXR0byIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJlY2xpcHNlaG9ubyIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJwcm90b2J1ZiIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50IiwidGFnIiA6ICJkZW1vIn0sCgkJICAgIHsia2V5IiA6ICJqc29uc2NoZW1hIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKCQkgICAgeyJrZXkiIDogImF6dXJlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKIHsia2V5IiA6ICJvcGVuYXBpIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkgICAgeyJrZXkiIDogImx3bTJtIiwgInBsdWdpblR5cGUiOiAiaW1wb3J0ZXIiLCAibmFtZSIgOiAiTHdNMk0iICwgImZpbGVUeXBlIiA6ICIueG1sIiwgImRlc2NyaXB0aW9uIiA6ICJDb252ZXJ0cyBMd00yTSBkZXNjcmlwdGlvbnMgdG8gVm9ydG8iLCAiZW5kcG9pbnQiIDogImh0dHBzOi8vaXlubzNtengxaC5leGVjdXRlLWFwaS5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS9EZXZlbG9wbWVudCJ9XQ=="
# SAM CLI local
plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vMTI3LjAuMC4xOjMwMDAifSwKCQkJeyJrZXkiIDogImVjbGlwc2VkaXR0byIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cDovLzEyNy4wLjAuMTozMDAwIn0sCgkJICAgIHsia2V5IiA6ICJlY2xpcHNlaG9ubyIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cDovLzEyNy4wLjAuMTozMDAwIn0sCgkJICAgIHsia2V5IiA6ICJwcm90b2J1ZiIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cDovLzEyNy4wLjAuMTozMDAwIiwidGFnIiA6ICJkZW1vIn0sCgkJICAgIHsia2V5IiA6ICJqc29uc2NoZW1hIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vMTI3LjAuMC4xOjMwMDAiLCJ0YWciIDogImRlbW8ifSwKCQkgICAgeyJrZXkiIDogImF6dXJlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vMTI3LjAuMC4xOjMwMDAiLCJ0YWciIDogImRlbW8ifSwKIHsia2V5IiA6ICJvcGVuYXBpIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vMTI3LjAuMC4xOjMwMDAifSwKCQkgICAgeyJrZXkiIDogImx3bTJtIiwgInBsdWdpblR5cGUiOiAiaW1wb3J0ZXIiLCAibmFtZSIgOiAiTHdNMk0iICwgImZpbGVUeXBlIiA6ICIueG1sIiwgImRlc2NyaXB0aW9uIiA6ICJDb252ZXJ0cyBMd00yTSBkZXNjcmlwdGlvbnMgdG8gVm9ydG8iLCAiZW5kcG9pbnQiIDogImh0dHA6Ly8xMjcuMC4wLjE6MzAwMCJ9XQ=="
# Generator runner
# plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vbG9jYWxob3N0OjgwODEvZ2VuZXJhdG9ycyJ9LAoJCQl7ImtleSIgOiAiZWNsaXBzZWRpdHRvIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vbG9jYWxob3N0OjgwODEvZ2VuZXJhdG9ycyJ9LAoJCSAgICB7ImtleSIgOiAiZWNsaXBzZWhvbm8iLCAicGx1Z2luVHlwZSI6ICJnZW5lcmF0b3IiLCAiYXBpVmVyc2lvbiIgOiAiMiIgLCAiZW5kcG9pbnQiIDogImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9nZW5lcmF0b3JzIn0sCiB7ImtleSIgOiAib3BlbmFwaSIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2dlbmVyYXRvcnMifSwKIHsia2V5IiA6ICJqc29uc2NoZW1hIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vbG9jYWxob3N0OjgwODEvZ2VuZXJhdG9ycyJ9XQ=="
# only openapi

#plugins : "W3sia2V5IiA6ICJvcGVuYXBpIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vMTI3LjAuMC4xOjMwMDAifV0="

#logging:
#  level:
#    root : ERROR
#    org.eclipse.vorto.repository.core.impl : DEBUG