server:
  contextPath: /

repo:
  configFile: vorto-repository-config-mysql.json

spring:
  datasource:
    url: jdbc:mysql://${db_url_domain}:3306/vorto_dev?autoReconnect=true
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    wait_timeout: 180
    validationInterval: 60
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
  hibernate:
    ddl-auto: validate
    
    
plugins : "[
			{\"key\" : \"boschiotsuite\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\"},
			{\"key\" : \"eclipseditto\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\"},
		    {\"key\" : \"eclipsehono\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\"},
		    {\"key\" : \"protobuf\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\",\"tag\" : \"demo\"},
		    {\"key\" : \"jsonschema\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\",\"tag\" : \"demo\"},
		    {\"key\" : \"azure\", \"pluginType\": \"generator\", \"apiVersion\" : \"2\" , \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\",\"tag\" : \"demo\"},
		    {\"key\" : \"lwm2m\", \"pluginType\": \"importer\", \"name\" : \"LwM2M\" , \"fileType\" : \".xml\", \"description\" : \"Converts LwM2M descriptions to Vorto\", \"endpoint\" : \"https://iyno3mzx1h.execute-api.eu-central-1.amazonaws.com/Development\"}  
		   ]"
