# docker-compose.yml
vorto-thingworx-generator-web:
  build: .
  container_name: vorto-thingworx-generator
  ports:
   - 9001:9001
  environment:
    - VORTO_SERVICE_REPOSITORYURL=http://192.168.99.100:8080/infomodelrepository/rest
    - SERVER_CONTEXTPATH=/vorto-thingworx
    - SERVER_PORT=9001
